
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)

set(LIB1_INCLUDE_DIRS "${_IMPORT_PREFIX}/include")


add_library(@PROJECT_NAME@ SHARED IMPORTED)

set_target_properties(@PROJECT_NAME@ PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "USING_LIB1_SHARED=1"
  INTERFACE_INCLUDE_DIRECTORIES "${LIB1_INCLUDE_DIRS}"
  IMPORTED_LOCATION "${LIB1_LIBRARIES}"
)

if(WIN32)
    set(LIB1_LIBRARIES "${_IMPORT_PREFIX}/lib/@CMAKE_STATIC_LIBRARY_PREFIX@@PROJECT_NAME@@CMAKE_STATIC_LIBRARY_SUFFIX@")
    set_target_properties(@PROJECT_NAME@ PROPERTIES
        IMPORTED_IMPLIB "${LIB1_LIBRARIES}"
    )
else()
    set(LIB1_LIBRARIES "${_IMPORT_PREFIX}/lib/@CMAKE_STATIC_LIBRARY_PREFIX@@PROJECT_NAME@@CMAKE_SHARED_MODULE_SUFFIX@")
    set_target_properties(@PROJECT_NAME@ PROPERTIES
    IMPORTED_LOCATION "${LIB1_LIBRARIES}"
    )
endif()

set_target_properties(@PROJECT_NAME@ PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS "USING_LIB1_SHARED=1"
    INTERFACE_INCLUDE_DIRECTORIES "${LIB1_INCLUDE_DIRS}"
)

set(_IMPORT_PREFIX)